# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d82916b7512d071b086882243a0ebcf24f32ea9c60b18fa0f73eeffd5bd10a3d1316d1ed9e541ad3c363bbd713bdf862f24a94d12f0bca5bd373cc20bff4233

test:
  secret_key_base: f74437dcbc00aaba066e4d46f2a17bc83f38fc56b43658dc452d822b04e93d0af6f26a98c1a6b07e1745db55da0a589dd0ebb12fa60db13937b9160bb94d0b26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
